### ISSUE TITLE
Un-named buffer on creating a new note

### ISSUE THREAD

**Issue by fugokidi** [gnebbia/kb#11]
## Expected Behavior
Vim should create a buffer with a name so that it can be saved after writing the note.

## Actual Behavior
When creating a new note, for example,
`kb add --title "ftp" --category "notes" --tags "protocol;network"`
Vim created an un-named buffer, the note cannot be saved.

## Specifications

  - Platform: Mac OS 10.15.5

**Comment by gnebbia** [comment]
Thanks for the report, but I am afraid that your version of kb is not updated.
Try to re-clone the repository and do:
   pip install --upgrade . # there is a dot at the end
within the main kb directory.
Let me know if it works.

**Comment by fugokidi** [comment]
@gnebbia You are right. After upgrading, it works perfectly now. Thank you.
