### ISSUE TITLE
Render Markdown articles

### ISSUE THREAD

**Issue by lewis262626** [gnebbia/kb#111]
## Expected Behavior

I write most of my articles using GitHub flavoured Markdown. At the moment, I just pipe the output of `kb` in to a CLI Markdown viewer such as `glow`, but it'd be great if this was built-in to `kb`.

## Actual Behavior

Markdown isn't rendered

## Steps to Reproduce the Problem

  1. View article in Markdown
  2. No rendered markdown

## Specifications

  - Version: kb 0.1.7
  - Platform: Mac M1
  - Subsystem: cli

**Comment by Andonome** [comment]
This would be great.

There are other options, so perhaps it could detect which Markdown readers are available, and then use one.  I usually use `mdcat`.

**Comment by gnebbia** [comment]
I would say that the more deps we add the more time it will drain from my side (since I am the only one working at the project at the moment). 
One suggestion here would just be to create a shell function or alias that pipes things to the tool you want as you are doing.
