### ISSUE TITLE
python3.6 not work 

### ISSUE THREAD

**Issue by yihong0618** [gnebbia/kb#12]
## Expected Behavior
`kb list` or `kb add` work fine 

## Actual Behavior
kb list or kb add cause exceptions
![image](https://user-images.githubusercontent.com/15976103/93730658-2c319a00-fbfc-11ea-97a8-534999a707a3.png)

I use docker-compose  works fine
## Steps to Reproduce the Problem

  1. using python3.6 
  2. install kb
  3. kb list

## Specifications

  - Version: python 3.6
  - Platform: windows
  - Subsystem: wsl1

**Comment by gnebbia** [comment]
Thanks for reporting, are you using the last version of kb?
If you don't know try to re-clone the repository and do a:

    pip install --upgrade . # yes it is a dot at the end

within the kb directory.
Let me know if it works.

**Comment by yihong0618** [comment]
Thank you for reply

No I am using the latest code 

Kind of locate the problem. maybe because python3.6 `pathlib` will not auto str Path
![image](https://user-images.githubusercontent.com/15976103/93733257-4ae95e00-fc07-11ea-89e9-5eb67f999493.png)

I changed the config file fix this?

![image](https://user-images.githubusercontent.com/15976103/93733262-59377a00-fc07-11ea-9f43-ba5b6374290f.png)

Can I take a pr? Or you have other idea?

![image](https://user-images.githubusercontent.com/15976103/93733286-78cea280-fc07-11ea-9f2a-baf2e042e48a.png)

**Comment by yihong0618** [comment]
@gnebbia 

Here...  seems solve in Python3.7

https://bugs.python.org/issue33496
