### ISSUE TITLE
status field does not show up in its correct place. shows up in the author column instead.

### ISSUE THREAD

**Issue by asadmoosvi** [gnebbia/kb#16]
The status value shows up in the author column when the author is not explicitly supplied.

Please have a look at this demonstration: [asciinema illustration](https://asciinema.org/a/Dyptl0FdvEE3ZTuO3Md1ULs0r).

**Comment by gnebbia** [comment]
Ok fixed it with the last commit! Thanks a lot!

upgrade it by doing:
    pip uninstall kb
then pull the last updates and do:
    pip install . # there is a dot 
within the kb directory.
Let me know if you still have problems.

**Comment by asadmoosvi** [comment]
It seems to have been fixed but maybe you forgot to remove these debug statements as they're showing up whenever a new artifact is added: https://github.com/gnebbia/kb/blob/c932b1a59b39b9b8a21243aeaf4fe1e5d9b3aec4/kb/commands/add.py#L80-L81

**Comment by gnebbia** [comment]
Ooops! Thanks! 
Ok should be removed!
Update again, and sorry!
Let me know if now it is ok!

**Comment by asadmoosvi** [comment]
Everything works perfectly now!

**Comment by gnebbia** [comment]
Thanks! Great!

**Comment by aIIclear** [comment]
> Ok fixed it with the last commit! Thanks a lot!
> 
> upgrade it by doing:
> pip uninstall kb
> then pull the last updates and do:
> pip install . # there is a dot
> within the kb directory.
> Let me know if you still have problems.

should i do this every time, or simple git pull will do?

**Comment by gnebbia** [comment]
Well if you do git pull, you get the latest release on master (which could be more unstable), while if you do:
 pip install -U kb-manager
you get the most recent stable release.
NOTE: for windows the most stable version is not very stable, we are working toward porting kb to windows as fully working (approx. next week).
