### ISSUE TITLE
Permission Issue When Reading Artifact In Editor (Windows)

### ISSUE THREAD

**Issue by MrADevelopers** [gnebbia/kb#23]
I am using windows 8.1
every thing seems to work fine its an excellent work.
Just one problem, when i use this command kb view -i 0 -e

it says permission denied error13

![err](https://user-images.githubusercontent.com/46569511/93858374-80f51380-fcd5-11ea-9029-103f9dff051c.jpg)

**Comment by gnebbia** [comment]
Thanks Sir! Yes I am aware of this issue, we are working toward resolving it!
If you find any other issues let me know!
Let's keep the issue open until it isn't solved!

**Comment by MrADevelopers** [comment]
Great! By the way good work.

**Comment by MrADevelopers** [comment]
I have one more question, is there any way to move .kb file in C://Users/user name/.kb 
to any other drive or location since if the windows get corrupted for any reason all the data will be lost ?

**Comment by gnebbia** [comment]
@MrADevelopers Thanks for your appreciation!
For what concerns the corruption of data, I have some words about it.
1 - We are working on a synchronization infrastructure that will be git-based, unluckily for this you should wait for version 0.2
2 - At the moment I suggest you frequently do:
    kb export
or if you only want to export raw data:
    kb export --data
So do it frequently and backup, then you can import the package exported by `kb export` back by doing:
    kb import <package_name>
3 - At the moment we decided that the user cannot choose the default position of the kb folder, maybe in the future we could customize the location, but still one would need a configuration file sitting in the home directory.

**Comment by gnebbia** [comment]
Another note about why I designed the `kb export --data`.
I added this option, since I thought that some user would like to export the raw data organized by categories as an archive, so
that you could:
1 - use (or import) this data with other software related to knowledge management
2 - restart from scratch with kb if the database in some way is corrupted, in this case, if you only have the data archive organized by directories you can do this:
Let's say you had three categories in kb, hence you will  have three directories in the data archive (e.g., default, cheatsheet, theory) now you can import your data back by doing:
    kb add path/to/default/* --category "default"
    kb add path/to/cheatsheet/* --category "cheatsheet"
    kb add path/to/theory/* --category "theory"
I hope that is clear!

**Comment by MrADevelopers** [comment]
Thank you! appreciate your clerifications

**Comment by yihong0618** [comment]
> Another note about why I designed the `kb export --data`.
> I added this option, since I thought that some user would like to export the raw data organized by categories as an archive, so
> that you could:
> 1 - use (or import) this data with other software related to knowledge management
> 2 - restart from scratch with kb if the database in some way is corrupted, in this case, if you only have the data archive organized by directories you can do this:
> Let's say you had three categories in kb, hence you will have three directories in the data archive (e.g., default, cheatsheet, theory) now you can import your data back by doing:
> kb add path/to/default/* --category "default"
> kb add path/to/cheatsheet/* --category "cheatsheet"
> kb add path/to/theory/* --category "theory"
> I hope that is clear!

Cool, I used to write an issues blog based on GitHub Actions [gitblog](https://github.com/yihong0618/gitblog)--In Chinese, 
I think I can combine issues and issues comments with your wonderful work -- `kb` like using [Python 
 log](https://github.com/yihong0618/gitblog/issues/43)

issue label is category and comment is one new `kb`, when issue or issue comment add, the GitHub action trigger, add it too kb, then export to file add auto commit.

Using that I can auto share my kb on GitHub, and grep in my local cmd.

**Comment by gnebbia** [comment]
@yihong0618 thanks Sir, and thanks a lot for your valuable help!

**Comment by MrADevelopers** [comment]
And pls share the installation directory of the project so I can have a loot at the source too.

**Comment by gnebbia** [comment]
Sorry ? What do you mean by the installation directory of the project ?
You mean where artifacts are saved? Look into $HOME/.kb/

**Comment by MrADevelopers** [comment]
No where the source code of the KB is, that handles all the commands etc.

**Comment by gnebbia** [comment]
The source code is on github you can get it by doing:
     git clone https://github.com/gnebbia/kb

**Comment by MrADevelopers** [comment]
Yeah but i want to know where it sits on my PC

**Comment by gnebbia** [comment]
Well this depends on your configuration, are you installing it with pip? do you have pyenv? are you using python from the app store or downloaded online? Are you using the git repo?
It really depends on how you installed kb.

**Comment by MrADevelopers** [comment]
i installed it from pip, i installed python from internet
(sorry i am not good at python)

**Comment by gnebbia** [comment]
It also depends on you python version then, I would suggest to use git and github to tinker with code!

**Comment by gnebbia** [comment]
This bug has been fixed! Update kb with git and everything will work!

**Comment by yihong0618** [comment]
> > Another note about why I designed the `kb export --data`.
> > I added this option, since I thought that some user would like to export the raw data organized by categories as an archive, so
> > that you could:
> > 1 - use (or import) this data with other software related to knowledge management
> > 2 - restart from scratch with kb if the database in some way is corrupted, in this case, if you only have the data archive organized by directories you can do this:
> > Let's say you had three categories in kb, hence you will have three directories in the data archive (e.g., default, cheatsheet, theory) now you can import your data back by doing:
> > kb add path/to/default/* --category "default"
> > kb add path/to/cheatsheet/* --category "cheatsheet"
> > kb add path/to/theory/* --category "theory"
> > I hope that is clear!
> 
> Cool, I used to write an issues blog based on GitHub Actions [gitblog](https://github.com/yihong0618/gitblog)--In Chinese,
> I think I can combine issues and issues comments with your wonderful work -- `kb` like using [Python log](https://github.com/yihong0618/gitblog/issues/43)
> 
> issue label is category and comment is one new `kb`, when issue or issue comment add, the GitHub action trigger, add it too kb, then export to file add auto commit.
> 
> Using that I can auto share my kb on GitHub, and grep in my local cmd.

@gnebbia 

Done! I combine the two system~ with [GItHub Actions](https://github.com/yihong0618/gitblog/blob/master/.github/workflows/generate_kb.yml)

Thank you for your great work!

![image](https://user-images.githubusercontent.com/15976103/94172074-9da36e00-fec4-11ea-97fb-ca21e1f0f8c2.png)

![image](https://user-images.githubusercontent.com/15976103/94172187-c461a480-fec4-11ea-8476-ca3e1c5046b6.png)

**Comment by gnebbia** [comment]
That's cool! I am happy to hear that! And again thanks for your contributions and helping me finding and solving bugs!
