### ISSUE TITLE
feature:  add --body  to add command for quick add kb

### ISSUE THREAD

**Issue by yihong0618** [gnebbia/kb#27]
Also for some automation.
Like 
``` 
kb add --title test --body 'hello\nnew feature request'
```
![image](https://user-images.githubusercontent.com/15976103/93988400-3cdc3e80-fdbb-11ea-8345-76d3fd5bfa12.png)
Can we add this feature?

**Comment by gnebbia** [comment]
Yes! Let me work on it!

**Comment by yihong0618** [comment]
I have done it？I think its simple. I can take a pr. But I am not sure you want it or not ~

**Comment by gnebbia** [comment]
Make the pull request! I think this can be useful!

**Comment by yihong0618** [comment]
Done
Thank you.

**Comment by gnebbia** [comment]
Added! Thanks Sir!

**Comment by yihong0618** [comment]
@gnebbia  seems not  upload to pypi yet?

**Comment by gnebbia** [comment]
@yihong0618 basically because this is still 0.1.3, as soon as I will fix other bugs (also minor bugs)
we can insert this as 0.1.4.
Anyway I think 0.1.4 will be released quite soon!

So help me finding other bugs ;)

**Comment by yihong0618** [comment]
Cool.
And I found a way to install the latest code using pip~

```shell
pip install git+https://github.com/gnebbia/kb
```

**Comment by gnebbia** [comment]
Thanks Sir, I am going to add it to the docs!
