### ISSUE TITLE
Feature to export all text based notes to a single file

### ISSUE THREAD

**Issue by darkLord19** [gnebbia/kb#29]
As the title says, how do you feel about having a feature to export all the text notes in a single text file with some specific format.

That'd be helpful if user for any reason want to move away from kb.

**Comment by gnebbia** [comment]
@darkLord19 let's discuss about it!
For this purpose I left the "export -d" (where "d" stands for "data").
This will basically export only the directories (each representing a category) and within these directories
the use has all the artifacts (i.e., files).

What do you mean by exporting all text notes to a single file ? So a single text file containing everything? What would be the scenario?

**Comment by darkLord19** [comment]
Yes correct. I'm assuming this tool will be noting timestamp of when some item has been added to kb and then for exporting, we can add entries in ascending ways in a txt file. So we'll have all the kb in a single file. I currently use this single file method to keep notes with the help of some shell functions. It helps searching for things easier and also it is extremely portable.

While we are at it. We can even add option to export data as json in case if someone wants to use their notes programmatically.

**Comment by gnebbia** [comment]
@darkLord19 thanks, well we can consider this feature for the next release!
