### ISSUE TITLE
Build a vscode Extension

### ISSUE THREAD

**Issue by wil1iam** [gnebbia/kb#35]
Hi there, i find the product  through @yihong0618 on twitter, and it's fantastic. I was wondering if you could build a vscode extension. Considering the popularity of vscode , the product will be a  smash-hit when the extension releases.

**Comment by gnebbia** [comment]
@gatsby101 that is a very cool idea! Unluckily I have basically no experience both in using and developing visual studio code extensions. Do you @yihong0618 have any knowledge about this?

**Comment by alshapton** [comment]
@gatsby101 what would the extension do ?

**Comment by alshapton** [comment]
I'm thinking here - maybe using VS code to store code snippets in a kb ?????
This would need the API at least

**Comment by gnebbia** [comment]
Instead of a vscode specific plugin, we implemented a rofi mode!
Take a look at rofi, is a good tool!
