### ISSUE TITLE
Distribute Arch Linux package

### ISSUE THREAD

**Issue by tgy** [gnebbia/kb#36]
It would be nice to be able to install kb on Arch Linux systems simply by doing `yay -S python-kb-manager`. This would require creating a package the way it is described here: https://wiki.archlinux.org/index.php/Python_package_guidelines

I never did it myself so it would take me time to learn the correct way of packaging python packages. But if no one here has time to do it, I can try.

**Comment by gnebbia** [comment]
I have the PKGBUILD ready, now I only have to read how to upload to AUR

**Comment by tgy** [comment]
well, that was fast :stuck_out_tongue_closed_eyes:

**Comment by gnebbia** [comment]
@tgy  ok done! It's in the AUR at the moment.
I created two packages:
kb (which is the stable version synchronized with pypi)
kb-git (which is the bleeding edge version synchronized with the git repo)

You can try:
    yay -S kb
or
    yay -S kb-git

**Comment by tgy** [comment]
@gnebbia thanks! seems to work well!

however, the best practice to package python software for Arch Linux is to call the package `python-<package>`.

so, if you want to respect the AUR's guideline, i would recommend calling the package `python-kb` and `python-kb-git` instead

better do it know than later when many people will have installed it. also, this would probably give you better chances to be merge to the community repositories

**Comment by gnebbia** [comment]
ok thanks @tgy good to know! So I am going to repackage them let's reopen the issue until it is solved

**Comment by gnebbia** [comment]
Ok reuploaded again as:
python-kb and python-kb-git!

Thanks for the suggestion!

**Comment by tgy** [comment]
awesome, i've installed `python-kb-git` and it works. now we can also think of creating a arch wiki page

**Comment by gnebbia** [comment]
@tgy that's a cool idea!
