### ISSUE TITLE
Updating status updates author instead

### ISSUE THREAD

**Issue by JoshuaEnglish** [gnebbia/kb#37]
## Expected Behavior

I tried to update the status of a document

## Actual Behavior

The Author was updated instead

## Steps to Reproduce the Problem

  1.  Added a file with a status of 'open'
  1.  Ran >kb update --id 2 -s closed
  1.  Did a verbose list and saw the author was 'closed' and the status was still 'open'

## Specifications

  - Version: 0.12
  - Platform: Windows 10
  - Subsystem:

**Comment by gnebbia** [comment]
Thanks Sir, fixed it! Unluckily the update function has still some quirks!
Now it works! Please update to the most recent version.
