### ISSUE TITLE
Missing Package: Metadata

### ISSUE THREAD

**Issue by wonderingwombat** [gnebbia/kb#5]
## Expected Behavior
expected 'kb list' to list execute. 

## Actual Behavior
The following error was raised: 
```
Traceback (most recent call last):
  File "/usr/bin/kb", line 33, in <module>
    sys.exit(load_entry_point('kb==0.1.1', 'console_scripts', 'kb')())
  File "/usr/bin/kb", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: kb

```
I expect that there is an additional requirement that needs to be specified? This running on Ubuntu 20.04.

**Comment by gnebbia** [comment]
I think the problem may be related to your python distribution,
are you using pyenv?

**Comment by wonderingwombat** [comment]
I'm not using pyenv, but I am using Python 3.8, which is not listed under the Classifiers in the setup.py file. Is there any reason 3.8 shouldn't work?

**Comment by gnebbia** [comment]
No, there is no reason indeed! I tested it under python 3.8 mainly.
Could you try to install pyenv and install a clean version of python 3.8?

Because it may be a problem related to your environment I suspect.

**Comment by wonderingwombat** [comment]
Thanks, you were right, I deleted everything and installed with pip as per the latest instructions and that is working. Cheers.

**Comment by gnebbia** [comment]
Cool!
