### ISSUE TITLE
Create a new knowledge base

### ISSUE THREAD

**Issue by alshapton** [gnebbia/kb#51]
## Expected Behavior
I believe that a function like `kb --init` would be advantageous to create a new knowledgeable, when someone who wishes to erase a knowledgeable and create a new one from scratch

**Comment by gnebbia** [comment]
Ok tell me more about this functionality...

**Comment by alshapton** [comment]
This may form part of a wider concept - Maybe I'd like a number of knowledge bases - some for work, some for personal stuff etc...... in  the longer term, I may want to share my knowledge with team members.

**Comment by gnebbia** [comment]
Yes that is an interesting idea... 
I tought about this some weeks ago... We should think about how to set this..
I thought something like...

kb base add   "work" # creates a new knowledge base for work
kb base switch "work" # Sswitches to the work knowledge base
kb base delete # deletes a knowledge base
kb base import # imports a knowledge base
kb base export # exports a knowledgee base

**Comment by alshapton** [comment]
I think we need to stabilise the existing codebase first. Plus we need a way to copy/move knowledgeable items from one kb to another..... maybe a niche feature - possibly  we should wait for V2 to do this.....

**Comment by alshapton** [comment]
> Yes that is an interesting idea...
> I tought about this some weeks ago... We should think about how to set this..
> I thought something like...
> 
kb base add "work" # creates a new knowledge base for work
kb base switch "work" # Switches to the work knowledge base
kb base delete # deletes a knowledge base
kb base import # imports a knowledge base
kb base export # exports a knowledge base
kb base copy 1 "other" # copy an item from the current knowledge base to another.
kb base move 1 "other" # move an item from the current knowledge base to another.

**Comment by alshapton** [comment]
- [ ] kb base list # list all knowledgebases
- [ ] kb base current # show the current knowledgebase
- [ ] kb base move 3 "other" # move item from current to "other" knowledgebase
- [ ] kb base copy 3 "other" # copy item from current to "other" knowledgebase
- [ ] migration script from version 0.1.5 and earlier
- [ ] kb base add "work" # creates a new knowledge base for work
- [ ] kb base switch "work" # Sswitches to the work knowledge base
- [ ] kb base delete # deletes a knowledge base
- [ ] kb base import # imports a knowledge base
- [ ] kb base export # exports a knowledgee base

**Comment by alshapton** [comment]
kb base add "work" # creates a new knowledge base for work
kb base switch "work" # Sswitches to the work knowledge base
kb base delete # deletes a knowledge base
kb base import # imports a knowledge base
kb base export # exports a knowledgee base

**Comment by alshapton** [comment]
completed and issue closed - changes in development
