### ISSUE TITLE
[Bug] Program fails to gracefully handle non-existent path for new artifact 

### ISSUE THREAD

**Issue by jmhickman** [gnebbia/kb#55]
## Expected Behavior
Printed error describing that the path indicated by the command doesn't exist.

## Actual Behavior

Stack trace because `shutil` can't open a write handle to the file.

## Steps to Reproduce the Problem

  1. After installing `kb` normally via `pip` and activating the aliases, run `kba /doesnt/exist/path`
  

## Specifications

  - Version: 0.1.4
  - Platform: Linux
  - Subsystem: ?

**Comment by gnebbia** [comment]
This issue has been fixed by adding a print message for the error! Update kb from git!
