### ISSUE TITLE
Add "stats" functionality

### ISSUE THREAD

**Issue by alshapton** [gnebbia/kb#61]
## Expected Behavior

New function:

**stats** 

will return number of artefacts, number of tags, number of categories, number of authors and anything else that seems useful.

**Comment by gnebbia** [comment]
Good Idea!

**Comment by alshapton** [comment]
I'll add this in my breaks between working on the API !!!
(just for a change of coding !!!!!)

**Comment by alshapton** [comment]
@gnebbia Cant work out why the stats function isn't listed in the list  of commands - halted my work straight away - any chance you can have a quick look at what I've done wrong please ?
Here's the commit :(https://github.com/gnebbia/kb/commit/ffbefa9afa2530b7785f5050d2daa7dede99a44e)

**Comment by alshapton** [comment]
Closed by PR #67
