### ISSUE TITLE
Error when deleting by title from command line

### ISSUE THREAD

**Issue by alshapton** [gnebbia/kb#70]
## Expected Behavior

The artefact should have been deleted

## Actual Behavior

Traceback (most recent call last):
  File "/usr/local/bin/kb", line 33, in <module>
    sys.exit(load_entry_point('kb-manager', 'console_scripts', 'kb')())
  File "/Users/shaptona/MyProjects/kb/kb/main.py", line 62, in main
    dispatch(cmd, cmd_params, config=DEFAULT_CONFIG)
  File "/Users/shaptona/MyProjects/kb/kb/main.py", line 54, in dispatch
    return COMMANDS[function](*args, **kwargs)
  File "/Users/shaptona/MyProjects/kb/kb/commands/delete.py", line 50, in delete
    print("Artifact {id} removed!".format(args["id"]))
KeyError: 'id'
## Steps to Reproduce the Problem

  1. kb delete -t <title>

## Specifications

  - Version: 0.1.5
  - Platform:MacOS
  - Subsystem:

**Comment by alshapton** [comment]
This is in the development branch. Pdoxuction use is not impaired.

**Comment by gnebbia** [comment]
Indeed I saw that this bug is only related to the dev branch... It does not affect the main branch, can you confirm this?

**Comment by alshapton** [comment]
Yes - I can - I'm on to it !

**Comment by alshapton** [comment]
Closed by [This commit](https://github.com/gnebbia/kb/commit/5684d60da3e449c158c5a2bf47a098fe4d96a346) to develop branch
