### ISSUE TITLE
[request] use bat instead of cat

### ISSUE THREAD

**Issue by Ramiferous** [gnebbia/kb#80]
Is it possible to configure kb to use bat instead of cat when viewing notes and cheatsheets? for large files this will allow for easy scrolling.

**Comment by gnebbia** [comment]
Actually kb does not use cat, it just prints the artifacts line by line without calling an external program.

**Comment by gnebbia** [comment]
anyway you could try to setup a function in your .bashrc or .profile file, such as:

function kbvbat(){ kbv "$1" | bat; }

Of course rename the function as you wish.

**Comment by Ramiferous** [comment]
> function kbvbat(){ kbv "$1" | bat; }

This does pipe the output through bat, however it exits out to a prompt meaning that you still cannot use the keyboard to scroll up/down.

**Comment by gnebbia** [comment]
Sorry I don't understand the issue, I tried and  I am scrolling just fine, did you try it?
The program does not enforce the use of cat or any other pager.
Try the above solution and let me know.

**Comment by Ramiferous** [comment]
Nevermind, I got it working. Thanks
