### ISSUE TITLE
Possible README error

### ISSUE THREAD

**Issue by BrettHolton** [gnebbia/kb#86]
## Expected Behavior
kb Add launches editor

## Actual Behavior
kb add fails to find editor

## Steps to Reproduce the Problem

  1.follow instructions to install for windows powershell
$env:EDITOR="C:\path\to\editor\here.exe"
[System.Environment]::SetEnvironmentVariable('EDITOR','"C:\path\to\editor\here.exe"', [System.EnvironmentVariableTarget]::User)

This appears to be missing the ' on the first line
I could not make it work until I added single quotes
$env:EDITOR='"C:\path\to\editor\here.exe"'

I am using notepad++ installed to C:Program Files\Notepad++
## Specifications

  - Version:1.6
  - Platform:Windows
  - Subsystem:

**Comment by gnebbia** [comment]
Thanks a lot Sir, the issue has been fixed in the documentation.
Thanks again for your help and contribution.
Greetings
