### ISSUE TITLE
XDG Compliance

### ISSUE THREAD

**Issue by eankeen** [gnebbia/kb#87]
## Expected Behavior

Puts `kb` data in `"${XDG_DATA_HOME:-$HOME/.local/share}/kb"`

It would be great to follow the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and place application
data files in `$XDG_DATA_HOME/kb`, if it exists, and fall back to `$HOME/.local/share/kb` if that environment variable does not exist. It was mentioned offhand in [this thread](https://github.com/gnebbia/kb/issues/84#issuecomment-812488911), but I would like to make an issue to address this :)

## Actual Behavior

`kb` data put in `~/.kb`.

## Steps to Reproduce the Problem

Execute a `kb` command

## Specifications

  - Version: 0.1.5
  - Platform: Linux
  - Subsystem: Arch

**Comment by gnebbia** [comment]
Dear Sir, XDG compliance is surely a priority, hence with the next release the default directory will change its position.
Let's keep this open until it is fixed.

**Comment by gnebbia** [comment]
Dear Sir, XDG compliance has been implemented. Of course it will break some sort of compatibility with previous versions.

A fix can be users moving $HOME/.kb into $HOME/.local/share/kb or into the XDG_DATA_HOME directory.

At the moment this is of course only implemented within the git version but as soon as 0.1.7 will come out this will be the default.

**Comment by eankeen** [comment]
Thank you very much! I am excited to see this change in the new release :)

**Comment by eankeen** [comment]
@gnebbia I checked some of the changes, and I just wanted to be sure of something

Could it be that the following code matches your description a bit more:

```py
BASE_PATH = Path(os.environ.get("XDG_DATA_HOME",Path(Path.home(),".local","share")),"kb")
```

It looks like that with the current changes, if `XDG_DATA_HOME` is defined, then `PATH_KB` would be set to `$XDG_DATA_HOME` and `PATH_KB_GIT` would be set to `$XDG_DATA_HOME/.git`, rather than `$XDG_DATA_HOME/kb` and `$XDG_DATA_HOME/kb/.git`, respectively

**Comment by gnebbia** [comment]
Yes you are right, my bad. 

This the latest commit should fix this for good. Thanks to your suggestion and testing. Really, thanks a lot!
