### ISSUE TITLE
Can we update category/tags after it's created?

### ISSUE THREAD

**Issue by tiendo1011** [gnebbia/kb#90]
I think it's nice if we can update it.
Also, I think it will be more convenient if the title/category/tags are included inside the note as well, so we don't need to specify title/category/tags in the command line when we add a new note, and we can update it easily when we want later.

So I imagine a flow like this:
1. Adding new note: type `kba`, this will open a new file in the $EDITOR will the following structure:
```
# title: 
# category:
# tags:
```
Then we can add it there, it's nice to be able to add it in the editor, instead of from the command line

2. Edit old note: type `kbe 0`, this will open the note, and allow us to update everything, from the content to title/category/tags

**Comment by gnebbia** [comment]
Dear tiendo1011, unluckily this was unwanted from the beginning, the idea of kb was really to separate content from metadata about content.
