### ISSUE TITLE
Asking for confirmation before deleting the artifact

### ISSUE THREAD

**Issue by tiendo1011** [gnebbia/kb#93]
## Expected Behavior
When running `kb delete --id some_id`, It should ask for confirmation before deleting the artifact

## Actual Behavior
It deletes the artifact right away

## Specifications

  - Version: 0.1.6
  - Platform: Ubuntu 20.04

I think we should allow an option to specify if we want confirmation before deleting the artifact, since sometime accidently deleting an artifact can have a wreak havoc effect.

**Comment by gnebbia** [comment]
Dear Madame/Sir, your suggestion made a lot of sense and was implemented.
Now when you try to remove an artifact it will ask for confirmation (default behavior).

Anyway, there is also the possibility to force the removal by using the `-f/--force` option for the delete command.

You can either download/install from git or wait for the new release 0.1.7 that will come out in the next weeks.

Happy with that?

**Comment by tiendo1011** [comment]
Yeah that's awesome, thank you @gnebbia

**Comment by tiendo1011** [comment]
Hi @gnebbia, can you release 0.1.7?
