### ISSUE TITLE
[request] merge db option

### ISSUE THREAD

**Issue by pfr-dev** [gnebbia/kb#95]
I use kb on two different machines, and both have their own separate database. Sometimes I need info on one machine from the other database and I then need to backup my current db and import the other, then restore the original afterwards. It would be quite convenient if I was able to merge both date bases together.

Is it possible to add a `kb merge` option to add this functionality?

Thanks

**Comment by gnebbia** [comment]
@pfr-dev thanks for your interest in kb and your message.
Actually synchronization is now one of the big issues we would like to solve with kb.

My suggestion is to use a workaround solution based on git at the moment.

So basically I would create some aliases to manage the a git repository containing the whole knowledge base directory.
If you installed kb 0.1.6 the directory you should git is `$HOME/.kb` while if you are using the latest kb version (which is XDG compliant) then the directory that has to be under git control is `$HOME/.local/share/kb/`.

Keep in mind that any further feature related to the merge of knowledge bases would still be based on git so this workflow would be compatible with eventual synchronization integrations.

**Comment by pfr-dev** [comment]
Thank you, I will try this
